// src/config/dotenvXConfig.js
import dotEnvX from '@dotenvx/dotenvx';
dotEnvX.config();

export default {
    HOST: process.env.HOST || 'NO ENCONTRE VARIABLE DE ENTORNO',
    PORT: process.env.PORT || 'NO ENCONTRE PORT',
    API_URL: process.env.API_URL || 'NO SE ENCONTRO VARIABLE DE ENTORNO',
    CONNECTION_STRING: process.env.CONNECTION_STRING || 'NO SE ENCONTRO VARIABLE DE ENTORNO',
    DATABASE: process.env.DATABASE || 'NO SE ENCONTRO VARIABLE DE ENTORNO',
    DB_USER: process.env.DB_USER || 'NO SE ENCONTRO VARIABLE DE ENTORNO',
    DB_PASSWORD: process.env.DB_PASSWORD || 'NO SE ENCONTRO VARIABLE DE ENTORNO',

    COSMOSDB_ENDPOINT: process.env.COSMOSDB_ENDPOINT || 'NO ENCONTRE VARIABLE DE ENTORNO',
    COSMOSDB_KEY: process.env.COSMOSDB_KEY || 'NO ENCONTRE VARIABLE DE ENTORNO',
    COSMOSDB_DATABASE: process.env.COSMOSDB_DATABASE || 'NO ENCONTRE VARIABLE DE ENTORNO',
    COSMOSDB_CONTAINER: process.env.COSMOSDB_CONTAINER || 'NO ENCONTRE VARIABLE DE ENTORNO'
};